
server:
  port: 8081
#  servlet:
#    context-path: /product

spring:
#  application:
#    name: product
  datasource:
    url: jdbc:mysql://localhost:3306/jmm_parlour?serverTimezone=EST5EDT
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        
logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.jmm.capital: DEBUG
    org.hibernate: ERROR
  file: /Users/ramjisoni/jmm_parlour/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"

   
    
    

     
    
  
 
